### ISSUE TITLE
Docker registry missing

### ISSUE THREAD

**Issue by davidholsgrove** [returntocorp/semgrep-network-broker#53]
The documentation points to https://github.com/returntocorp/semgrep-network-broker/pkgs/container/semgrep-network-broker for prebuilt docker images, but is giving a 404 - as is pulling previously released image tags

**Comment by tpetr** [comment]
Apologies @davidholsgrove, it looks like this was an unintended side effect of our org rename (`returntocorp` --> `semgrep`). I'll update the documentation to point to `ghcr.io/semgrep/semgrep-network-broker`
